// DEPENDENCIES
const firebase = require("../util/firebase.js");
const PDFDocument = require("../util/pdf.js");
const mail = require("../util/mail.js");
const Appointment = firebase.db.Appointment;

// CONSTANTS
const subjectText = 'MySmartMedical - Appointment Sign In';
const appIcon = "./assets/app_icon.png";
const coverPageText =
  "This content was generated by MySmartMedical on behalf of the user";

// PROTOTYPES
Appointment.prototype.signIn = async function() {
  let user = this.user;
  await user.fetch();
  let institution = this.institution;
  await institution.fetch();
  let pages = [{
    title: "General Info",
    paragraphs: ["p1", "p2"]
  }];
  let pdf = PDFDocument.genFormattedDoc(appIcon, coverPageText, pages);
  let filename = `${user.firstName}_${user.lastName}_medical_info.pdf`;
  let text =
    `${user.firstName} ${user.lastName} has signed for ${this.name}. Attached is their medical information.`
  let email = institution.email;
  await mail.sendWithAttachment(email, subjectText, text, filename, pdf);
  await this.update({
    signedIn: true
  });
}

// STATICS
Appointment.exists = async key => await Appointment.getKeysExist([key]);

Appointment.create = async params => {
  return await Appointment.createByAutoKey({
    user: params.user,
    institution: params.institution,
    name: params.name,
    time: params.time,
    signedIn: false
  });
}

// EXPORTS
module.exports = Appointment;
